language: node_js
node_js:
  - '12'
services:
  - adminDB
cache: yarn
branches:
  only:
    - master
env:
  global:
    - PORT=5000
    - MONGODB_URL={MONGODB_URL}
    - JWT_SECRET=thisisasamplesecret
    - JWT_ACCESS_EXPIRATION_MINUTES=30
    - JWT_REFRESH_EXPIRATION_DAYS=30
script:
  - yarn lint
  - yarn doctorApp
after_success: yarn coverage:coveralls
